freelancer:
    path:     /
    defaults: { _controller: "ProjetFreelancerBundle:Freelancer:index" }

freelancer_show:
    path:     /{id}/show
    defaults: { _controller: "ProjetFreelancerBundle:Freelancer:show" }

freelancer_new:
    path:     /new
    defaults: { _controller: "ProjetFreelancerBundle:Freelancer:new" }

freelancer_create:
    path:     /create
    defaults: { _controller: "ProjetFreelancerBundle:Freelancer:create" }
    requirements: { _method: post }

freelancer_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProjetFreelancerBundle:Freelancer:edit" }

freelancer_update:
    path:     /{id}/update
    defaults: { _controller: "ProjetFreelancerBundle:Freelancer:update" }
    requirements: { _method: post|put }

freelancer_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProjetFreelancerBundle:Freelancer:delete" }
    requirements: { _method: post|delete }
