<?php

namespace Proxies\__CG__\Projet\FreelancerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reclamation extends \Projet\FreelancerBundle\Entity\Reclamation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Reclamation' . "\0" . 'titre', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Reclamation' . "\0" . 'message', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Reclamation' . "\0" . 'id', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Reclamation' . "\0" . 'projet', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Reclamation' . "\0" . 'jobowner', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Reclamation' . "\0" . 'freelancer');
        }

        return array('__isInitialized__', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Reclamation' . "\0" . 'titre', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Reclamation' . "\0" . 'message', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Reclamation' . "\0" . 'id', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Reclamation' . "\0" . 'projet', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Reclamation' . "\0" . 'jobowner', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Reclamation' . "\0" . 'freelancer');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Reclamation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessage($message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessage', array($message));

        return parent::setMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', array());

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjet(\Projet\FreelancerBundle\Entity\Projet $projet = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjet', array($projet));

        return parent::setProjet($projet);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjet', array());

        return parent::getProjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobowner(\Projet\FreelancerBundle\Entity\JobOwner $jobowner = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobowner', array($jobowner));

        return parent::setJobowner($jobowner);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobowner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobowner', array());

        return parent::getJobowner();
    }

    /**
     * {@inheritDoc}
     */
    public function setFreelancer(\Projet\FreelancerBundle\Entity\Projet $freelancer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFreelancer', array($freelancer));

        return parent::setFreelancer($freelancer);
    }

    /**
     * {@inheritDoc}
     */
    public function getFreelancer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFreelancer', array());

        return parent::getFreelancer();
    }

}
