<?php

namespace Proxies\__CG__\Projet\FreelancerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Projet extends \Projet\FreelancerBundle\Entity\Projet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'nom', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'description', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'affecte', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'prixmin', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'prixmax', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'finalise', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'dateprojet', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'idOffre', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'id', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'idJobOwner', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'idCategorie', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'idFreelancer');
        }

        return array('__isInitialized__', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'nom', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'description', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'affecte', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'prixmin', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'prixmax', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'finalise', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'dateprojet', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'idOffre', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'id', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'idJobOwner', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'idCategorie', '' . "\0" . 'Projet\\FreelancerBundle\\Entity\\Projet' . "\0" . 'idFreelancer');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Projet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setAffecte($affecte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAffecte', array($affecte));

        return parent::setAffecte($affecte);
    }

    /**
     * {@inheritDoc}
     */
    public function getAffecte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffecte', array());

        return parent::getAffecte();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixmin($prixmin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixmin', array($prixmin));

        return parent::setPrixmin($prixmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixmin', array());

        return parent::getPrixmin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixmax($prixmax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixmax', array($prixmax));

        return parent::setPrixmax($prixmax);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixmax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixmax', array());

        return parent::getPrixmax();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinalise($finalise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinalise', array($finalise));

        return parent::setFinalise($finalise);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinalise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinalise', array());

        return parent::getFinalise();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateprojet($dateprojet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateprojet', array($dateprojet));

        return parent::setDateprojet($dateprojet);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateprojet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateprojet', array());

        return parent::getDateprojet();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdOffre($idOffre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdOffre', array($idOffre));

        return parent::setIdOffre($idOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdOffre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOffre', array());

        return parent::getIdOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdJobOwner(\Projet\FreelancerBundle\Entity\JobOwner $idJobOwner = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdJobOwner', array($idJobOwner));

        return parent::setIdJobOwner($idJobOwner);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdJobOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdJobOwner', array());

        return parent::getIdJobOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCategorie(\Projet\FreelancerBundle\Entity\Categorie $idCategorie = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCategorie', array($idCategorie));

        return parent::setIdCategorie($idCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCategorie', array());

        return parent::getIdCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdFreelancer(\Projet\FreelancerBundle\Entity\Freelancer $idFreelancer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdFreelancer', array($idFreelancer));

        return parent::setIdFreelancer($idFreelancer);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdFreelancer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdFreelancer', array());

        return parent::getIdFreelancer();
    }

}
